version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234Ab*
      MYSQL_ROOT_HOST: "localhost"
      MYSQL_DATABASE: db
      MYSQL_USER: ed
      MYSQL_PASSWORD: 1234Ab*
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  api:
    build: ./api
    ports:
      - "8080:8080"
  socket:
    build: ./socket
    ports:
      - "8765:8765"
  